(define-public python-aider-chat
  (package
    (name "python-aider-chat")
    (version "0.86.2")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/Aider-AI/aider")
             (commit (string-append "v" version))))
       (file-name (git-file-name name version))
       (sha256
        (base32 "0qm0m9k1l26h2pnzn98bss2na672787w1bp29mfpviflqc2dg9cd"))))
    (build-system pyproject-build-system)
    (propagated-inputs (list python-aiohappyeyeballs
                             python-aiohttp
                             python-aiosignal
                             python-annotated-doc
                             python-annotated-types
                             python-anyio
                             python-asgiref
                             python-attrs
                             python-backoff
                             python-beautifulsoup4
                             python-certifi
                             python-cffi
                             python-charset-normalizer
                             python-click
                             python-configargparse
                             python-diff-match-patch
                             python-diskcache
                             python-distro
                             python-fastapi
                             python-fastuuid
                             python-filelock
                             python-frozenlist
                             python-fsspec
                             python-gitdb
                             python-gitpython
                             python-grep-ast
                             python-h11
                             python-hf-xet
                             python-httpcore
                             python-httpx
                             python-huggingface-hub
                             python-idna
                             python-importlib-resources
                             python-jinja2
                             python-jiter
                             python-json5
                             python-jsonschema
                             python-jsonschema-specifications
                             python-litellm
                             python-markdown-it-py
                             python-markupsafe
                             python-mccabe
                             python-mdurl
                             python-mixpanel
                             python-mslex
                             python-multidict
                             python-networkx
                             python-numpy
                             python-openai
                             python-orjson
                             python-oslex
                             python-packaging
                             python-pathspec
                             python-pexpect
                             python-pillow
                             python-posthog
                             python-prompt-toolkit
                             python-propcache
                             python-psutil
                             python-ptyprocess
                             python-pycparser
                             python-pydantic
                             python-pydantic-core
                             python-pydub
                             python-pygments
                             python-pypandoc
                             python-pyperclip
                             python-dateutil
                             python-dotenv
                             python-pyyaml
                             python-referencing
                             python-regex
                             python-requests
                             python-rich
                             python-rpds-py
                             python-scipy
                             python-shellingham
                             python-shtab
                             python-six
                             python-smmap
                             python-sniffio
                             python-socksio
                             python-sounddevice
                             python-soundfile
                             python-soupsieve
                             python-starlette
                             python-tiktoken
                             python-tokenizers
                             python-tqdm
                             python-tree-sitter-c-sharp
                             python-tree-sitter-embedded-template
                             python-tree-sitter-language-pack
                             python-tree-sitter-yaml
                             python-typer
                             python-typer-slim
                             python-typing-extensions
                             python-typing-inspection
                             python-urllib3
                             python-watchfiles
                             python-wcwidth
                             python-yarl
                             python-zipp))
    (native-inputs (list python-annotated-doc
                         python-build
                         python-certifi
                         python-cffi
                         python-cfgv
                         python-charset-normalizer
                         python-click
                         python-codespell
                         python-cogapp
                         python-contourpy
                         python-cryptography
                         python-cycler
                         python-distlib
                         python-filelock
                         python-fonttools
                         python-google-api-core
                         python-google-auth
                         python-google-cloud-bigquery
                         python-google-cloud-core
                         python-google-crc32c
                         python-google-resumable-media
                         python-googleapis-common-protos
                         python-grpcio
                         python-grpcio-status
                         python-identify
                         python-idna
                         python-imgcat
                         python-iniconfig
                         python-kiwisolver
                         python-lox
                         python-markdown-it-py
                         python-matplotlib
                         python-mdurl
                         python-nodeenv
                         python-numpy
                         python-packaging
                         python-pandas
                         python-pillow
                         python-pip
                         python-pip-tools
                         python-platformdirs
                         python-pluggy
                         python-proto-plus
                         python-protobuf
                         python-pyasn1
                         python-pyasn1-modules
                         python-pycparser
                         python-pygments
                         python-pyparsing
                         python-pyproject-hooks
                         python-pytest
                         python-pytest-env
                         python-dateutil
                         python-pytz
                         python-pyyaml
                         python-requests
                         python-rich
                         python-rsa
                         python-semver
                         python-setuptools
                         python-setuptools-scm
                         python-shellingham
                         python-six
                         python-typer
                         python-typing-extensions
                         python-tzdata
                         python-urllib3
                         python-uv
                         python-virtualenv))
    (home-page "https://github.com/Aider-AI/aider")
    (synopsis "Aider is AI pair programming in your terminal")
    (description "Aider is AI pair programming in your terminal.")
    (license #f)))

